#!/usr/bin/env python3
"""Append missing i18n keys to non-English TOML files."""

import re
from pathlib import Path

I18N_DIR = Path(__file__).parent / "i18n"

# All translations keyed by language code
TRANSLATIONS = {
    "fr": {
        "skip_to_content": "Aller au contenu",
        "download_cloud_cta": "Ouvrir Valoryx Cloud",
        "download_cloud_description": "Aucune installation nécessaire. Créez votre espace de travail en quelques secondes. Nous gérons l'infrastructure, les mises à jour et les sauvegardes.",
        "download_cloud_free_note": "Plan gratuit : 1 espace de travail · 3 éditeurs · 50 pages publiées",
        "download_cloud_pill1": "Aucune configuration requise",
        "download_cloud_pill2": "Mises à jour automatiques",
        "download_cloud_pill3": "Plan gratuit permanent",
        "download_cloud_prefer_selfhosted": "Vous préférez le contrôle total ?",
        "download_cloud_switch_selfhosted": "Téléchargez l'édition auto-hébergée",
        "download_cloud_title": "Commencez avec Valoryx Cloud",
        "download_deploy_cloud": "Cloud",
        "download_deploy_selfhosted": "Auto-hébergé",
        "hero_cta_cloud": "Essayer Cloud Gratuit",
        "hero_cta_cloud_sub": "Nous hébergeons · Pas de configuration · Démarrez en 30 secondes",
        "hero_cta_selfhosted": "Télécharger Gratuit",
        "hero_cta_selfhosted_sub": "Auto-hébergé · Binaire unique · Gratuit pour toujours",
        "tpl_ai_desc": "Laissez les agents IA écrire et mettre à jour vos docs via MCP.",
        "tpl_ai_title": "Documentation Maintenue par IA",
        "tpl_api_desc": "Publiez des docs API qui vivent dans votre dépôt git.",
        "tpl_api_title": "Documentation API",
        "tpl_badge": "Cas d'utilisation & Modèles de départ",
        "tpl_changelog_desc": "Tenez les utilisateurs informés avec des mises à jour versionnées dans git.",
        "tpl_changelog_title": "Changelog Produit",
        "tpl_compliance_desc": "Documents SOC2/HIPAA avec historique de versions.",
        "tpl_compliance_title": "Documentation de Conformité",
        "tpl_cta_btn": "Commencer Gratuitement",
        "tpl_cta_text": "Choisissez un modèle, connectez votre dépôt et publiez en minutes. Gratuit pour les équipes jusqu'à 5.",
        "tpl_cta_title": "Commencez à Construire",
        "tpl_filter_all": "Tout",
        "tpl_filter_api": "Docs API",
        "tpl_filter_kb": "Base de Connaissances",
        "tpl_filter_oss": "Open Source",
        "tpl_filter_wiki": "Wiki d'Équipe",
        "tpl_hero_subtitle": "Commencez avec une structure éprouvée. Personnalisez tout.",
        "tpl_hero_title": "Modèles de Documentation",
        "tpl_how_subtitle": "Trois étapes de zéro à la documentation publiée.",
        "tpl_how_title": "Comment ça Marche",
        "tpl_kb_desc": "Des docs internes que votre équipe maintient réellement.",
        "tpl_kb_title": "Base de Connaissances Ingénierie",
        "tpl_oss_desc": "De belles docs à partir de votre README.",
        "tpl_oss_title": "Docs de Projet Open Source",
        "tpl_step1_text": "Créez un espace de travail et connectez votre dépôt git. Vos fichiers Markdown existants sont importés automatiquement.",
        "tpl_step1_title": "Créer un Espace de Travail",
        "tpl_step2_text": "Utilisez l'éditeur WYSIWYG ou poussez depuis votre IDE. Chaque modification se synchronise bidirectionnellement avec git.",
        "tpl_step2_title": "Écrire ou Importer",
        "tpl_step3_text": "Un clic pour publier une documentation belle et consultable. Domaines personnalisés, thèmes et contrôle d'accès inclus.",
        "tpl_step3_title": "Publier",
        "vs_badge": "Comparaison Honnête",
        "vs_competitor_wins_subtitle": "Nous croyons aux comparaisons honnêtes. Voici où la concurrence a un avantage.",
        "vs_cta_btn": "Commencer",
        "vs_cta_text": "Gratuit pour les équipes jusqu'à 5 éditeurs. Sans carte de crédit. Auto-hébergé ou Docker.",
        "vs_cta_title": "Essayez Valoryx Gratuitement",
        "vs_diff_text": "Valoryx combine la synchronisation git bidirectionnelle, un serveur Model Context Protocol et un graphe de contexte qui comprend les relations entre vos pages. Les agents IA ne se contentent pas de lire vos docs — ils comprennent la structure, les dépendances et les lacunes. Aucune autre plateforme de documentation n'offre cette combinaison.",
        "vs_diff_title": "La Différence Clé",
        "vs_gb_tldr1": "Valoryx stocke chaque page comme un vrai commit git avec synchronisation bidirectionnelle. GitBook offre une intégration git unidirectionnelle.",
        "vs_gb_tldr2": "Valoryx est un binaire unique auto-hébergé que vous possédez. GitBook est un SaaS cloud uniquement sans option auto-hébergée.",
        "vs_gb_tldr3": "Valoryx expose un serveur MCP pour que les agents IA puissent lire et écrire les docs. GitBook a une IA intégrée mais pas de protocole agent.",
        "vs_gb_win1_text": "GitBook existe depuis 2014 avec une grande communauté, des intégrations étendues et une infrastructure éprouvée à grande échelle.",
        "vs_gb_win1_title": "Écosystème Mature",
        "vs_gb_win2_text": "GitBook fournit des informations détaillées sur les recherches des utilisateurs, les pages les plus visitées et les points d'abandon des lecteurs.",
        "vs_gb_win2_title": "Analytique de Recherche Intégrée",
        "vs_gb_win3_text": "GitBook inclut une recherche et une assistance à l'écriture alimentées par l'IA nativement, sans configuration d'agent externe.",
        "vs_gb_win3_title": "Fonctionnalités IA Intégrées",
        "vs_hero_subtitle": "Une comparaison équitable pour la documentation développeur.",
        "vs_row_ai": "Fonctionnalités IA Intégrées",
        "vs_row_analytics": "Analytique de Recherche",
        "vs_row_dataown": "Propriété des Données",
        "vs_row_freetier": "Plan Gratuit",
        "vs_row_gitsync": "Synchronisation Git Bidirectionnelle",
        "vs_row_mcp": "Serveur MCP (Agents IA)",
        "vs_row_published": "Sites de Docs Publiés",
        "vs_row_search": "Recherche Plein Texte",
        "vs_row_selfhosted": "Auto-Hébergé",
        "vs_row_singlebinary": "Déploiement Binaire Unique",
        "vs_row_wysiwyg": "Éditeur WYSIWYG",
        "vs_table_subtitle": "Côte à côte sur les fonctionnalités qui comptent le plus.",
        "vs_table_title": "Comparaison des Fonctionnalités",
        "vs_tldr_title": "TL;DR",
        "vs_valoryx_wins_title": "Où Valoryx Gagne",
        "vs_win1_text": "Chaque page est un vrai fichier dans un vrai dépôt git. La synchronisation bidirectionnelle signifie que vous pouvez éditer dans l'interface web ou votre IDE et les deux restent synchronisés. GitBook ne synchronise que dans un sens.",
        "vs_win1_title": "Architecture Git-Native",
        "vs_win2_text": "Valoryx expose un serveur Model Context Protocol pour que Claude, Cursor et d'autres outils IA puissent lire, rechercher et mettre à jour votre documentation programmatiquement.",
        "vs_win2_title": "MCP pour les Agents IA",
        "vs_win3_text": "Téléchargez un binaire, exécutez-le. Pas de conteneurs nécessaires, pas de dépendance cloud. Vos données restent sur votre infrastructure avec un contrôle total.",
        "vs_win3_title": "Auto-Hébergé, Binaire Unique",
        "vs_win4_text": "Votre contenu est du Markdown dans git. Si vous partez, vous emportez tout. Pas de format propriétaire, pas d'étape d'export, pas de données otage.",
        "vs_win4_title": "Pas de Verrouillage Fournisseur",
    },
    "de": {
        "skip_to_content": "Zum Inhalt springen",
        "download_cloud_cta": "Valoryx Cloud öffnen",
        "download_cloud_description": "Keine Installation erforderlich. Erstellen Sie Ihren Arbeitsbereich in Sekunden. Wir kümmern uns um Infrastruktur, Updates und Backups.",
        "download_cloud_free_note": "Kostenloser Plan: 1 Arbeitsbereich · 3 Editoren · 50 veröffentlichte Seiten",
        "download_cloud_pill1": "Kein Setup erforderlich",
        "download_cloud_pill2": "Automatische Updates",
        "download_cloud_pill3": "Dauerhaft kostenloser Plan",
        "download_cloud_prefer_selfhosted": "Bevorzugen Sie volle Kontrolle?",
        "download_cloud_switch_selfhosted": "Laden Sie die selbstgehostete Edition herunter",
        "download_cloud_title": "Starten Sie mit Valoryx Cloud",
        "download_deploy_cloud": "Cloud",
        "download_deploy_selfhosted": "Self-Hosted",
        "hero_cta_cloud": "Cloud Kostenlos Testen",
        "hero_cta_cloud_sub": "Wir hosten · Kein Setup · Start in 30 Sekunden",
        "hero_cta_selfhosted": "Kostenlos Herunterladen",
        "hero_cta_selfhosted_sub": "Self-Hosted · Einzelnes Binary · Für immer kostenlos",
        "tpl_ai_desc": "Lassen Sie KI-Agenten Ihre Docs über MCP schreiben und aktualisieren.",
        "tpl_ai_title": "KI-gepflegte Dokumentation",
        "tpl_api_desc": "Veröffentlichen Sie API-Docs, die in Ihrem Git-Repo leben.",
        "tpl_api_title": "API-Dokumentation",
        "tpl_badge": "Anwendungsfälle & Startvorlagen",
        "tpl_changelog_desc": "Halten Sie Nutzer mit versionierten Updates informiert.",
        "tpl_changelog_title": "Produkt-Changelog",
        "tpl_compliance_desc": "SOC2/HIPAA-Dokumente mit Versionshistorie.",
        "tpl_compliance_title": "Compliance-Dokumentation",
        "tpl_cta_btn": "Kostenlos Starten",
        "tpl_cta_text": "Wählen Sie eine Vorlage, verbinden Sie Ihr Repo und veröffentlichen Sie in Minuten. Kostenlos für Teams bis 5.",
        "tpl_cta_title": "Starten Sie",
        "tpl_filter_all": "Alle",
        "tpl_filter_api": "API-Docs",
        "tpl_filter_kb": "Wissensdatenbank",
        "tpl_filter_oss": "Open Source",
        "tpl_filter_wiki": "Team-Wiki",
        "tpl_hero_subtitle": "Beginnen Sie mit einer bewährten Struktur. Passen Sie alles an.",
        "tpl_hero_title": "Dokumentationsvorlagen",
        "tpl_how_subtitle": "Drei Schritte von Null zu veröffentlichter Dokumentation.",
        "tpl_how_title": "So funktioniert's",
        "tpl_kb_desc": "Interne Docs, die Ihr Team tatsächlich pflegt.",
        "tpl_kb_title": "Engineering-Wissensdatenbank",
        "tpl_oss_desc": "Schöne Docs aus Ihrer README.",
        "tpl_oss_title": "Open-Source-Projekt-Docs",
        "tpl_step1_text": "Erstellen Sie einen Arbeitsbereich und verbinden Sie Ihr Git-Repo. Ihre vorhandenen Markdown-Dateien werden automatisch importiert.",
        "tpl_step1_title": "Arbeitsbereich Erstellen",
        "tpl_step2_text": "Nutzen Sie den WYSIWYG-Editor oder pushen Sie aus Ihrer IDE. Jede Änderung synchronisiert sich bidirektional mit Git.",
        "tpl_step2_title": "Schreiben oder Importieren",
        "tpl_step3_text": "Ein Klick zum Veröffentlichen schöner, durchsuchbarer Dokumentation. Eigene Domains, Themes und Zugriffskontrolle inklusive.",
        "tpl_step3_title": "Veröffentlichen",
        "vs_badge": "Ehrlicher Vergleich",
        "vs_competitor_wins_subtitle": "Wir glauben an ehrliche Vergleiche. Hier hat die Konkurrenz einen Vorteil.",
        "vs_cta_btn": "Loslegen",
        "vs_cta_text": "Kostenlos für Teams bis 5 Editoren. Keine Kreditkarte erforderlich. Self-Hosted oder Docker.",
        "vs_cta_title": "Valoryx Kostenlos Testen",
        "vs_diff_text": "Valoryx kombiniert bidirektionale Git-Synchronisation, einen Model Context Protocol Server und einen Kontext-Graphen, der versteht, wie Ihre Seiten zusammenhängen. KI-Agenten lesen nicht nur Ihre Docs — sie verstehen Struktur, Abhängigkeiten und Lücken. Keine andere Dokumentationsplattform bietet diese Kombination.",
        "vs_diff_title": "Der Entscheidende Unterschied",
        "vs_gb_tldr1": "Valoryx speichert jede Seite als echten Git-Commit mit bidirektionaler Synchronisation. GitBook bietet nur einseitige Git-Integration.",
        "vs_gb_tldr2": "Valoryx ist ein einzelnes selbstgehostetes Binary, das Ihnen gehört. GitBook ist reines Cloud-SaaS ohne Self-Hosting-Option.",
        "vs_gb_tldr3": "Valoryx stellt einen MCP-Server bereit, damit KI-Agenten Docs lesen und schreiben können. GitBook hat integrierte KI, aber kein Agent-Protokoll.",
        "vs_gb_win1_text": "GitBook existiert seit 2014 mit großer Community, umfangreichen Integrationen und bewährter Infrastruktur im großen Maßstab.",
        "vs_gb_win1_title": "Ausgereiftes Ökosystem",
        "vs_gb_win2_text": "GitBook liefert detaillierte Einblicke in Nutzer-Suchen, meistbesuchte Seiten und Absprungpunkte der Leser.",
        "vs_gb_win2_title": "Integrierte Such-Analytik",
        "vs_gb_win3_text": "GitBook beinhaltet native KI-gestützte Suche und Schreibhilfe ohne externe Agenten-Konfiguration.",
        "vs_gb_win3_title": "Integrierte KI-Funktionen",
        "vs_hero_subtitle": "Ein fairer Vergleich für Entwickler-Dokumentation.",
        "vs_row_ai": "Integrierte KI-Funktionen",
        "vs_row_analytics": "Such-Analytik",
        "vs_row_dataown": "Datenhoheit",
        "vs_row_freetier": "Kostenloser Plan",
        "vs_row_gitsync": "Bidirektionale Git-Synchronisation",
        "vs_row_mcp": "MCP-Server (KI-Agenten)",
        "vs_row_published": "Veröffentlichte Doc-Sites",
        "vs_row_search": "Volltextsuche",
        "vs_row_selfhosted": "Self-Hosted",
        "vs_row_singlebinary": "Single-Binary-Deployment",
        "vs_row_wysiwyg": "WYSIWYG-Editor",
        "vs_table_subtitle": "Seite an Seite bei den wichtigsten Funktionen.",
        "vs_table_title": "Funktionsvergleich",
        "vs_tldr_title": "TL;DR",
        "vs_valoryx_wins_title": "Wo Valoryx Gewinnt",
        "vs_win1_text": "Jede Seite ist eine echte Datei in einem echten Git-Repo. Bidirektionale Synchronisation bedeutet: Bearbeiten Sie in der Web-UI oder Ihrer IDE — beides bleibt synchron. GitBook synchronisiert nur in eine Richtung.",
        "vs_win1_title": "Git-Native Architektur",
        "vs_win2_text": "Valoryx stellt einen Model Context Protocol Server bereit, damit Claude, Cursor und andere KI-Tools Ihre Dokumentation programmatisch lesen, suchen und aktualisieren können.",
        "vs_win2_title": "MCP für KI-Agenten",
        "vs_win3_text": "Laden Sie ein Binary herunter, starten Sie es. Keine Container nötig, keine Cloud-Abhängigkeit. Ihre Daten bleiben auf Ihrer Infrastruktur mit voller Kontrolle.",
        "vs_win3_title": "Self-Hosted, Einzelnes Binary",
        "vs_win4_text": "Ihr Content ist Markdown in Git. Wenn Sie gehen, nehmen Sie alles mit. Kein proprietäres Format, kein Export-Schritt, keine Datengeiselnahme.",
        "vs_win4_title": "Kein Vendor Lock-In",
    },
    "es": {
        "skip_to_content": "Ir al contenido",
        "download_cloud_cta": "Abrir Valoryx Cloud",
        "download_cloud_description": "Sin instalación necesaria. Crea tu espacio de trabajo en segundos. Nosotros nos encargamos de la infraestructura, actualizaciones y copias de seguridad.",
        "download_cloud_free_note": "Plan gratuito: 1 espacio de trabajo · 3 editores · 50 páginas publicadas",
        "download_cloud_pill1": "Sin configuración requerida",
        "download_cloud_pill2": "Actualizaciones automáticas",
        "download_cloud_pill3": "Plan gratuito permanente",
        "download_cloud_prefer_selfhosted": "¿Prefieres el control total?",
        "download_cloud_switch_selfhosted": "Descarga la edición auto-alojada",
        "download_cloud_title": "Comienza con Valoryx Cloud",
        "download_deploy_cloud": "Cloud",
        "download_deploy_selfhosted": "Auto-alojado",
        "hero_cta_cloud": "Probar Cloud Gratis",
        "hero_cta_cloud_sub": "Nosotros alojamos · Sin configuración · Empieza en 30 segundos",
        "hero_cta_selfhosted": "Descargar Gratis",
        "hero_cta_selfhosted_sub": "Auto-alojado · Binario único · Gratis para siempre",
        "tpl_ai_desc": "Deja que los agentes IA escriban y actualicen tus docs vía MCP.",
        "tpl_ai_title": "Documentación Mantenida por IA",
        "tpl_api_desc": "Publica docs API que viven en tu repositorio git.",
        "tpl_api_title": "Documentación API",
        "tpl_badge": "Casos de Uso y Plantillas",
        "tpl_changelog_desc": "Mantén a los usuarios informados con actualizaciones versionadas en git.",
        "tpl_changelog_title": "Changelog del Producto",
        "tpl_compliance_desc": "Documentos SOC2/HIPAA con historial de versiones.",
        "tpl_compliance_title": "Documentación de Cumplimiento",
        "tpl_cta_btn": "Comenzar Gratis",
        "tpl_cta_text": "Elige una plantilla, conecta tu repositorio y publica en minutos. Gratis para equipos de hasta 5.",
        "tpl_cta_title": "Empieza a Construir",
        "tpl_filter_all": "Todo",
        "tpl_filter_api": "Docs API",
        "tpl_filter_kb": "Base de Conocimiento",
        "tpl_filter_oss": "Open Source",
        "tpl_filter_wiki": "Wiki de Equipo",
        "tpl_hero_subtitle": "Comienza con una estructura probada. Personaliza todo.",
        "tpl_hero_title": "Plantillas de Documentación",
        "tpl_how_subtitle": "Tres pasos de cero a documentación publicada.",
        "tpl_how_title": "Cómo Funciona",
        "tpl_kb_desc": "Docs internos que tu equipo realmente mantiene.",
        "tpl_kb_title": "Base de Conocimiento de Ingeniería",
        "tpl_oss_desc": "Docs bonitos desde tu README.",
        "tpl_oss_title": "Docs de Proyecto Open Source",
        "tpl_step1_text": "Configura un espacio de trabajo y conecta tu repositorio git. Tus archivos Markdown existentes se importan automáticamente.",
        "tpl_step1_title": "Crear Espacio de Trabajo",
        "tpl_step2_text": "Usa el editor WYSIWYG o haz push desde tu IDE. Cada cambio se sincroniza bidireccionalmente con git.",
        "tpl_step2_title": "Escribir o Importar",
        "tpl_step3_text": "Un clic para publicar documentación bonita y buscable. Dominios personalizados, temas y control de acceso incluidos.",
        "tpl_step3_title": "Publicar",
        "vs_badge": "Comparación Honesta",
        "vs_competitor_wins_subtitle": "Creemos en comparaciones honestas. Aquí es donde la competencia tiene ventaja.",
        "vs_cta_btn": "Comenzar",
        "vs_cta_text": "Gratis para equipos de hasta 5 editores. Sin tarjeta de crédito. Auto-alojado o Docker.",
        "vs_cta_title": "Prueba Valoryx Gratis",
        "vs_diff_text": "Valoryx combina sincronización git bidireccional, un servidor Model Context Protocol y un grafo de contexto que entiende cómo se relacionan tus páginas. Los agentes IA no solo leen tus docs — entienden la estructura, dependencias y lagunas. Ninguna otra plataforma de documentación ofrece esta combinación.",
        "vs_diff_title": "La Diferencia Clave",
        "vs_gb_tldr1": "Valoryx almacena cada página como un commit git real con sincronización bidireccional. GitBook ofrece integración git unidireccional.",
        "vs_gb_tldr2": "Valoryx es un binario único auto-alojado que posees. GitBook es SaaS solo en la nube sin opción auto-alojada.",
        "vs_gb_tldr3": "Valoryx expone un servidor MCP para que los agentes IA lean y escriban docs. GitBook tiene IA integrada pero sin protocolo de agentes.",
        "vs_gb_win1_text": "GitBook existe desde 2014 con una gran comunidad, integraciones extensas e infraestructura probada a gran escala.",
        "vs_gb_win1_title": "Ecosistema Maduro",
        "vs_gb_win2_text": "GitBook proporciona información detallada sobre las búsquedas de usuarios, páginas más visitadas y puntos de abandono de lectores.",
        "vs_gb_win2_title": "Analítica de Búsqueda Integrada",
        "vs_gb_win3_text": "GitBook incluye búsqueda y asistencia de escritura impulsadas por IA de forma nativa, sin configuración de agentes externos.",
        "vs_gb_win3_title": "Funciones IA Integradas",
        "vs_hero_subtitle": "Una comparación justa para documentación de desarrolladores.",
        "vs_row_ai": "Funciones IA Integradas",
        "vs_row_analytics": "Analítica de Búsqueda",
        "vs_row_dataown": "Propiedad de Datos",
        "vs_row_freetier": "Plan Gratuito",
        "vs_row_gitsync": "Sincronización Git Bidireccional",
        "vs_row_mcp": "Servidor MCP (Agentes IA)",
        "vs_row_published": "Sitios de Docs Publicados",
        "vs_row_search": "Búsqueda de Texto Completo",
        "vs_row_selfhosted": "Auto-Alojado",
        "vs_row_singlebinary": "Despliegue de Binario Único",
        "vs_row_wysiwyg": "Editor WYSIWYG",
        "vs_table_subtitle": "Lado a lado en las funcionalidades que más importan.",
        "vs_table_title": "Comparación de Funcionalidades",
        "vs_tldr_title": "TL;DR",
        "vs_valoryx_wins_title": "Donde Valoryx Gana",
        "vs_win1_text": "Cada página es un archivo real en un repositorio git real. La sincronización bidireccional significa que puedes editar en la interfaz web o tu IDE y ambos permanecen sincronizados. GitBook solo sincroniza en una dirección.",
        "vs_win1_title": "Arquitectura Git-Native",
        "vs_win2_text": "Valoryx expone un servidor Model Context Protocol para que Claude, Cursor y otras herramientas IA puedan leer, buscar y actualizar tu documentación programáticamente.",
        "vs_win2_title": "MCP para Agentes IA",
        "vs_win3_text": "Descarga un binario, ejecútalo. Sin contenedores necesarios, sin dependencia de la nube. Tus datos permanecen en tu infraestructura con control total.",
        "vs_win3_title": "Auto-Alojado, Binario Único",
        "vs_win4_text": "Tu contenido es Markdown en git. Si te vas, te llevas todo. Sin formato propietario, sin paso de exportación, sin datos como rehén.",
        "vs_win4_title": "Sin Bloqueo de Proveedor",
    },
    "ru": {
        "skip_to_content": "Перейти к содержимому",
        "download_cloud_cta": "Открыть Valoryx Cloud",
        "download_cloud_description": "Установка не требуется. Создайте рабочее пространство за секунды. Мы берём на себя инфраструктуру, обновления и резервные копии.",
        "download_cloud_free_note": "Бесплатный план: 1 пространство · 3 редактора · 50 опубликованных страниц",
        "download_cloud_pill1": "Без настройки",
        "download_cloud_pill2": "Автоматические обновления",
        "download_cloud_pill3": "Бесплатный план навсегда",
        "download_cloud_prefer_selfhosted": "Предпочитаете полный контроль?",
        "download_cloud_switch_selfhosted": "Скачайте self-hosted версию",
        "download_cloud_title": "Начните с Valoryx Cloud",
        "download_deploy_cloud": "Cloud",
        "download_deploy_selfhosted": "Self-Hosted",
        "hero_cta_cloud": "Попробовать Cloud Бесплатно",
        "hero_cta_cloud_sub": "Мы хостим · Без настройки · Старт за 30 секунд",
        "hero_cta_selfhosted": "Скачать Бесплатно",
        "hero_cta_selfhosted_sub": "Self-hosted · Один бинарник · Бесплатно навсегда",
        "tpl_ai_desc": "Позвольте ИИ-агентам писать и обновлять документацию через MCP.",
        "tpl_ai_title": "Документация с ИИ-поддержкой",
        "tpl_api_desc": "Публикуйте API-документацию из вашего git-репозитория.",
        "tpl_api_title": "API-документация",
        "tpl_badge": "Сценарии использования и шаблоны",
        "tpl_changelog_desc": "Держите пользователей в курсе с версионными обновлениями.",
        "tpl_changelog_title": "Changelog продукта",
        "tpl_compliance_desc": "Документы SOC2/HIPAA с историей версий.",
        "tpl_compliance_title": "Документация соответствия",
        "tpl_cta_btn": "Начать Бесплатно",
        "tpl_cta_text": "Выберите шаблон, подключите репозиторий и опубликуйте за минуты. Бесплатно для команд до 5 человек.",
        "tpl_cta_title": "Начните Строить",
        "tpl_filter_all": "Все",
        "tpl_filter_api": "API Docs",
        "tpl_filter_kb": "База Знаний",
        "tpl_filter_oss": "Open Source",
        "tpl_filter_wiki": "Командная Вики",
        "tpl_hero_subtitle": "Начните с проверенной структуры. Настройте всё под себя.",
        "tpl_hero_title": "Шаблоны Документации",
        "tpl_how_subtitle": "Три шага от нуля до опубликованной документации.",
        "tpl_how_title": "Как это Работает",
        "tpl_kb_desc": "Внутренние документы, которые ваша команда действительно поддерживает.",
        "tpl_kb_title": "Инженерная База Знаний",
        "tpl_oss_desc": "Красивая документация из вашего README.",
        "tpl_oss_title": "Документация Open Source Проекта",
        "tpl_step1_text": "Создайте рабочее пространство и подключите git-репозиторий. Существующие Markdown-файлы импортируются автоматически.",
        "tpl_step1_title": "Создать Пространство",
        "tpl_step2_text": "Используйте WYSIWYG-редактор или пушьте из IDE. Каждое изменение синхронизируется двунаправленно с git.",
        "tpl_step2_title": "Писать или Импортировать",
        "tpl_step3_text": "Один клик для публикации красивой, поисковой документации. Собственные домены, темы и контроль доступа включены.",
        "tpl_step3_title": "Опубликовать",
        "vs_badge": "Честное Сравнение",
        "vs_competitor_wins_subtitle": "Мы верим в честные сравнения. Вот где у конкурентов есть преимущество.",
        "vs_cta_btn": "Начать",
        "vs_cta_text": "Бесплатно для команд до 5 редакторов. Без кредитной карты. Self-hosted или Docker.",
        "vs_cta_title": "Попробуйте Valoryx Бесплатно",
        "vs_diff_text": "Valoryx объединяет двунаправленную git-синхронизацию, сервер Model Context Protocol и граф контекста, который понимает связи между страницами. ИИ-агенты не просто читают документацию — они понимают структуру, зависимости и пробелы. Ни одна другая платформа не предлагает такую комбинацию.",
        "vs_diff_title": "Ключевое Отличие",
        "vs_gb_tldr1": "Valoryx хранит каждую страницу как реальный git-коммит с двунаправленной синхронизацией. GitBook предлагает одностороннюю git-интеграцию.",
        "vs_gb_tldr2": "Valoryx — это один self-hosted бинарник, который принадлежит вам. GitBook — облачный SaaS без возможности self-hosting.",
        "vs_gb_tldr3": "Valoryx предоставляет MCP-сервер для ИИ-агентов. GitBook имеет встроенный ИИ, но без протокола агентов.",
        "vs_gb_win1_text": "GitBook существует с 2014 года с большим сообществом, обширными интеграциями и проверенной инфраструктурой.",
        "vs_gb_win1_title": "Зрелая Экосистема",
        "vs_gb_win2_text": "GitBook предоставляет детальную аналитику поиска: запросы пользователей, популярные страницы и точки ухода читателей.",
        "vs_gb_win2_title": "Встроенная Аналитика Поиска",
        "vs_gb_win3_text": "GitBook включает нативный ИИ-поиск и помощь в написании без внешней конфигурации агентов.",
        "vs_gb_win3_title": "Встроенные ИИ-функции",
        "vs_hero_subtitle": "Честное сравнение для документации разработчиков.",
        "vs_row_ai": "Встроенные ИИ-функции",
        "vs_row_analytics": "Аналитика Поиска",
        "vs_row_dataown": "Владение Данными",
        "vs_row_freetier": "Бесплатный План",
        "vs_row_gitsync": "Двунаправленная Git-Синхронизация",
        "vs_row_mcp": "MCP-Сервер (ИИ-Агенты)",
        "vs_row_published": "Публикация Сайтов",
        "vs_row_search": "Полнотекстовый Поиск",
        "vs_row_selfhosted": "Self-Hosted",
        "vs_row_singlebinary": "Развёртывание Одним Бинарником",
        "vs_row_wysiwyg": "WYSIWYG-Редактор",
        "vs_table_subtitle": "Бок о бок по самым важным функциям.",
        "vs_table_title": "Сравнение Функций",
        "vs_tldr_title": "TL;DR",
        "vs_valoryx_wins_title": "Где Выигрывает Valoryx",
        "vs_win1_text": "Каждая страница — реальный файл в реальном git-репозитории. Двунаправленная синхронизация означает: редактируйте в веб-интерфейсе или IDE — оба остаются синхронизированными. GitBook синхронизирует только в одну сторону.",
        "vs_win1_title": "Git-Native Архитектура",
        "vs_win2_text": "Valoryx предоставляет сервер Model Context Protocol, чтобы Claude, Cursor и другие ИИ-инструменты могли программно читать, искать и обновлять вашу документацию.",
        "vs_win2_title": "MCP для ИИ-Агентов",
        "vs_win3_text": "Скачайте один бинарник, запустите его. Без контейнеров, без облачной зависимости. Ваши данные остаются на вашей инфраструктуре с полным контролем.",
        "vs_win3_title": "Self-Hosted, Один Бинарник",
        "vs_win4_text": "Ваш контент — Markdown в git. Если уходите — забираете всё. Без проприетарного формата, без шагов экспорта, без захвата данных.",
        "vs_win4_title": "Без Привязки к Вендору",
    },
    "uk": {
        "skip_to_content": "Перейти до вмісту",
        "download_cloud_cta": "Відкрити Valoryx Cloud",
        "download_cloud_description": "Встановлення не потрібне. Створіть робочий простір за секунди. Ми подбаємо про інфраструктуру, оновлення та резервні копії.",
        "download_cloud_free_note": "Безкоштовний план: 1 простір · 3 редактори · 50 опублікованих сторінок",
        "download_cloud_pill1": "Без налаштування",
        "download_cloud_pill2": "Автоматичні оновлення",
        "download_cloud_pill3": "Безкоштовний план назавжди",
        "download_cloud_prefer_selfhosted": "Віддаєте перевагу повному контролю?",
        "download_cloud_switch_selfhosted": "Завантажте self-hosted версію",
        "download_cloud_title": "Почніть з Valoryx Cloud",
        "download_deploy_cloud": "Cloud",
        "download_deploy_selfhosted": "Self-Hosted",
        "hero_cta_cloud": "Спробувати Cloud Безкоштовно",
        "hero_cta_cloud_sub": "Ми хостимо · Без налаштування · Старт за 30 секунд",
        "hero_cta_selfhosted": "Завантажити Безкоштовно",
        "hero_cta_selfhosted_sub": "Self-hosted · Один бінарник · Безкоштовно назавжди",
        "tpl_ai_desc": "Дозвольте ІІ-агентам писати та оновлювати документацію через MCP.",
        "tpl_ai_title": "Документація з ІІ-підтримкою",
        "tpl_api_desc": "Публікуйте API-документацію з вашого git-репозиторію.",
        "tpl_api_title": "API-документація",
        "tpl_badge": "Сценарії використання та шаблони",
        "tpl_changelog_desc": "Тримайте користувачів в курсі з версійними оновленнями.",
        "tpl_changelog_title": "Changelog продукту",
        "tpl_compliance_desc": "Документи SOC2/HIPAA з історією версій.",
        "tpl_compliance_title": "Документація відповідності",
        "tpl_cta_btn": "Почати Безкоштовно",
        "tpl_cta_text": "Оберіть шаблон, підключіть репозиторій та опублікуйте за хвилини. Безкоштовно для команд до 5 осіб.",
        "tpl_cta_title": "Починайте Будувати",
        "tpl_filter_all": "Усі",
        "tpl_filter_api": "API Docs",
        "tpl_filter_kb": "База Знань",
        "tpl_filter_oss": "Open Source",
        "tpl_filter_wiki": "Командна Вікі",
        "tpl_hero_subtitle": "Почніть з перевіреної структури. Налаштуйте все під себе.",
        "tpl_hero_title": "Шаблони Документації",
        "tpl_how_subtitle": "Три кроки від нуля до опублікованої документації.",
        "tpl_how_title": "Як це Працює",
        "tpl_kb_desc": "Внутрішні документи, які ваша команда дійсно підтримує.",
        "tpl_kb_title": "Інженерна База Знань",
        "tpl_oss_desc": "Гарна документація з вашого README.",
        "tpl_oss_title": "Документація Open Source Проекту",
        "tpl_step1_text": "Створіть робочий простір та підключіть git-репозиторій. Існуючі Markdown-файли імпортуються автоматично.",
        "tpl_step1_title": "Створити Простір",
        "tpl_step2_text": "Використовуйте WYSIWYG-редактор або пушіть з IDE. Кожна зміна синхронізується двонаправлено з git.",
        "tpl_step2_title": "Писати або Імпортувати",
        "tpl_step3_text": "Один клік для публікації гарної, пошукової документації. Власні домени, теми та контроль доступу включені.",
        "tpl_step3_title": "Опублікувати",
        "vs_badge": "Чесне Порівняння",
        "vs_competitor_wins_subtitle": "Ми віримо в чесні порівняння. Ось де конкуренти мають перевагу.",
        "vs_cta_btn": "Почати",
        "vs_cta_text": "Безкоштовно для команд до 5 редакторів. Без кредитної картки. Self-hosted або Docker.",
        "vs_cta_title": "Спробуйте Valoryx Безкоштовно",
        "vs_diff_text": "Valoryx поєднує двонаправлену git-синхронізацію, сервер Model Context Protocol та граф контексту, який розуміє зв'язки між сторінками. ІІ-агенти не просто читають документацію — вони розуміють структуру, залежності та прогалини. Жодна інша платформа не пропонує таку комбінацію.",
        "vs_diff_title": "Ключова Відмінність",
        "vs_gb_tldr1": "Valoryx зберігає кожну сторінку як реальний git-коміт з двонаправленою синхронізацією. GitBook пропонує односторонню git-інтеграцію.",
        "vs_gb_tldr2": "Valoryx — це один self-hosted бінарник, який належить вам. GitBook — хмарний SaaS без можливості self-hosting.",
        "vs_gb_tldr3": "Valoryx надає MCP-сервер для ІІ-агентів. GitBook має вбудований ІІ, але без протоколу агентів.",
        "vs_gb_win1_text": "GitBook існує з 2014 року з великою спільнотою, численними інтеграціями та перевіреною інфраструктурою.",
        "vs_gb_win1_title": "Зріла Екосистема",
        "vs_gb_win2_text": "GitBook надає детальну аналітику пошуку: запити користувачів, популярні сторінки та точки відходу читачів.",
        "vs_gb_win2_title": "Вбудована Аналітика Пошуку",
        "vs_gb_win3_text": "GitBook включає нативний ІІ-пошук та допомогу в написанні без зовнішньої конфігурації агентів.",
        "vs_gb_win3_title": "Вбудовані ІІ-функції",
        "vs_hero_subtitle": "Чесне порівняння для документації розробників.",
        "vs_row_ai": "Вбудовані ІІ-функції",
        "vs_row_analytics": "Аналітика Пошуку",
        "vs_row_dataown": "Володіння Даними",
        "vs_row_freetier": "Безкоштовний План",
        "vs_row_gitsync": "Двонаправлена Git-Синхронізація",
        "vs_row_mcp": "MCP-Сервер (ІІ-Агенти)",
        "vs_row_published": "Публікація Сайтів",
        "vs_row_search": "Повнотекстовий Пошук",
        "vs_row_selfhosted": "Self-Hosted",
        "vs_row_singlebinary": "Розгортання Одним Бінарником",
        "vs_row_wysiwyg": "WYSIWYG-Редактор",
        "vs_table_subtitle": "Пліч-о-пліч за найважливішими функціями.",
        "vs_table_title": "Порівняння Функцій",
        "vs_tldr_title": "TL;DR",
        "vs_valoryx_wins_title": "Де Виграє Valoryx",
        "vs_win1_text": "Кожна сторінка — реальний файл у реальному git-репозиторії. Двонаправлена синхронізація означає: редагуйте у веб-інтерфейсі або IDE — обидва залишаються синхронізованими. GitBook синхронізує лише в один бік.",
        "vs_win1_title": "Git-Native Архітектура",
        "vs_win2_text": "Valoryx надає сервер Model Context Protocol, щоб Claude, Cursor та інші ІІ-інструменти могли програмно читати, шукати та оновлювати вашу документацію.",
        "vs_win2_title": "MCP для ІІ-Агентів",
        "vs_win3_text": "Завантажте один бінарник, запустіть його. Без контейнерів, без хмарної залежності. Ваші дані залишаються на вашій інфраструктурі з повним контролем.",
        "vs_win3_title": "Self-Hosted, Один Бінарник",
        "vs_win4_text": "Ваш контент — Markdown в git. Якщо йдете — забираєте все. Без пропрієтарного формату, без кроків експорту, без захоплення даних.",
        "vs_win4_title": "Без Прив'язки до Вендора",
    },
}


def extract_existing_keys(content: str) -> set[str]:
    """Extract all [key_name] section headers from a TOML file."""
    return set(re.findall(r'^\[(\w+)\]', content, re.MULTILINE))


def format_toml_entries(keys_and_values: dict[str, str]) -> str:
    """Format key-value pairs as Hugo i18n TOML entries."""
    lines = []
    for key, value in keys_and_values.items():
        # Escape any double quotes inside the value
        escaped = value.replace('"', '\\"')
        lines.append(f'[{key}]')
        lines.append(f'other = "{escaped}"')
    return '\n'.join(lines)


def main():
    for lang, translations in TRANSLATIONS.items():
        filepath = I18N_DIR / f"{lang}.toml"
        if not filepath.exists():
            print(f"WARNING: {filepath} does not exist, skipping")
            continue

        content = filepath.read_text(encoding="utf-8")
        existing_keys = extract_existing_keys(content)

        missing = {k: v for k, v in translations.items() if k not in existing_keys}

        if not missing:
            print(f"{lang}.toml: all keys already present (0 missing)")
            continue

        # Build the block to append
        block = f"\n\n# ── Missing keys added by translate_missing.py ─────────────────────────────\n"
        block += format_toml_entries(missing)
        block += "\n"

        # Ensure file ends with newline before appending
        if not content.endswith("\n"):
            block = "\n" + block

        filepath.write_text(content + block, encoding="utf-8")
        print(f"{lang}.toml: appended {len(missing)} missing keys")


if __name__ == "__main__":
    main()
